Zadanie 10 3
rpwieczorek/project-pizzeria pull request #3
Opened 2022-01-19 23:05 UTC by rpwieczorek

2022-01-20 20:36 UTC, lduraj90 commented on src/js/components/Booking.js
> +      if(
Myślę, że takie z formatowanie byłoby bardziej czytelne:
``` if(!allAvailable
        && thisBooking.booked[thisBooking.date][thisBooking.hour].includes(tableId)
      ) { ...
      }```

2022-01-20 20:42 UTC, lduraj90 commented on src/js/components/Booking.js
> +    fetch(url, options);
Funkcja fetch zwraca tzw. Promise (http://kursjs.pl/kurs/ajax/promise.php). W momencie poprawnego wykonania kodu zostanie wywołany callback zaimplementowanych w metodzie `then` ( `fetch().then(callback)` ). Jako, ze promisy są formą implementacji asynchronicznej, może się zdarzyć, że wykonasz funkcję makeBooked, a chwilę później fetch zwróci błąd - z punktu widzenia UI user zarezerwował stolik, ale backend tej informacji nie dostał.

Wywołaj metodę makeBooked wewnątrz callbacku przekazanego do metody `then`

2022-01-20 20:43 UTC, lduraj90 requested changes
Poprawki

2022-01-22 15:31 UTC, rpwieczorek commented on src/js/components/Booking.js
> +      if(
poprawione

2022-01-22 15:31 UTC, rpwieczorek commented on src/js/components/Booking.js
> +    fetch(url, options);
poprawione

2022-01-24 17:25 UTC, lduraj90 commented on src/js/components/Booking.js
> +    fetch(url, options).then(thisBooking.makeBooked(payload.date, payload.hour, payload.duration, payload.table));
Musisz to wywołanie jeszcze opakować w funkcję anonimową. Teraz to wywołujesz tę funkcję od razu, a jako callback przekazujesz to co zwraca metoda makeBooked

2022-02-10 09:12 UTC, lduraj90 approved these changes

2022-02-10 09:28 UTC, merged